name = "ORCA"
uuid = "a8967ba7-180c-42ff-a42b-62a6bf227abe"
version = "0.1.0"

[deps]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CommunityDetection = "d427f087-d71a-5a1b-ace0-b93392eea9ff"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Leiden = "e5cf005d-d64d-44d4-821e-2384bf4ace83"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
NetworkDynamics = "22e9dc34-2a0d-11e9-0de0-8588d035468b"
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
